[build]
  publish = "dist"
  command = "npm ci && npm install vite@4.4.5 && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
